storage_dir: "storage"
env_dir: "setup/.venv/" # Path to the virtual environment. If you have installed the venv in a different location, make sure to change this.
huggingface_hub_username: "PLACEHOLDER"
