storage_dir: "PLACEHOLDER"
huggingface_hub_username: "Dhananjay99"
env_dir: "setup/.venv/" # Path to the virtual environment. If you have installed the venv in a different location, make sure to change this.